//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="station", Namespace="http://tempuri.org/")]
    public partial class station : object
    {
        
        private string station_IDField;
        
        private string station_locationField;
        
        private string station_nameField;
        
        private string station_photoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string station_ID
        {
            get
            {
                return this.station_IDField;
            }
            set
            {
                this.station_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string station_location
        {
            get
            {
                return this.station_locationField;
            }
            set
            {
                this.station_locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string station_name
        {
            get
            {
                return this.station_nameField;
            }
            set
            {
                this.station_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string station_photo
        {
            get
            {
                return this.station_photoField;
            }
            set
            {
                this.station_photoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attraction", Namespace="http://tempuri.org/")]
    public partial class Attraction : object
    {
        
        private int attraction_IDField;
        
        private string attraction_locationField;
        
        private string attraction_nameField;
        
        private string attraction_photoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int attraction_ID
        {
            get
            {
                return this.attraction_IDField;
            }
            set
            {
                this.attraction_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string attraction_location
        {
            get
            {
                return this.attraction_locationField;
            }
            set
            {
                this.attraction_locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string attraction_name
        {
            get
            {
                return this.attraction_nameField;
            }
            set
            {
                this.attraction_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string attraction_photo
        {
            get
            {
                return this.attraction_photoField;
            }
            set
            {
                this.attraction_photoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfStation", Namespace="http://tempuri.org/", ItemName="station")]
    public class ArrayOfStation : System.Collections.Generic.List<ServiceReference1.station>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AttractionsNearStations", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AttractionsNearStationsResponse> AttractionsNearStationsAsync(ServiceReference1.AttractionsNearStationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StationsNearAttractions", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.StationsNearAttractionsResponse> StationsNearAttractionsAsync(ServiceReference1.StationsNearAttractionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CoolOrNot", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CoolOrNotAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAttraction", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.DeleteAttractionResponse> DeleteAttractionAsync(ServiceReference1.DeleteAttractionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchAttraction", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SearchAttractionResponse> SearchAttractionAsync(ServiceReference1.SearchAttractionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttractionsNearStationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttractionsNearStations", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AttractionsNearStationsRequestBody Body;
        
        public AttractionsNearStationsRequest()
        {
        }
        
        public AttractionsNearStationsRequest(ServiceReference1.AttractionsNearStationsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AttractionsNearStationsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.station st;
        
        public AttractionsNearStationsRequestBody()
        {
        }
        
        public AttractionsNearStationsRequestBody(ServiceReference1.station st)
        {
            this.st = st;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttractionsNearStationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AttractionsNearStationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AttractionsNearStationsResponseBody Body;
        
        public AttractionsNearStationsResponse()
        {
        }
        
        public AttractionsNearStationsResponse(ServiceReference1.AttractionsNearStationsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AttractionsNearStationsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Attraction[] AttractionsNearStationsResult;
        
        public AttractionsNearStationsResponseBody()
        {
        }
        
        public AttractionsNearStationsResponseBody(ServiceReference1.Attraction[] AttractionsNearStationsResult)
        {
            this.AttractionsNearStationsResult = AttractionsNearStationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StationsNearAttractionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StationsNearAttractions", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.StationsNearAttractionsRequestBody Body;
        
        public StationsNearAttractionsRequest()
        {
        }
        
        public StationsNearAttractionsRequest(ServiceReference1.StationsNearAttractionsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StationsNearAttractionsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Attraction at;
        
        public StationsNearAttractionsRequestBody()
        {
        }
        
        public StationsNearAttractionsRequestBody(ServiceReference1.Attraction at)
        {
            this.at = at;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StationsNearAttractionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StationsNearAttractionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.StationsNearAttractionsResponseBody Body;
        
        public StationsNearAttractionsResponse()
        {
        }
        
        public StationsNearAttractionsResponse(ServiceReference1.StationsNearAttractionsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StationsNearAttractionsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfStation StationsNearAttractionsResult;
        
        public StationsNearAttractionsResponseBody()
        {
        }
        
        public StationsNearAttractionsResponseBody(ServiceReference1.ArrayOfStation StationsNearAttractionsResult)
        {
            this.StationsNearAttractionsResult = StationsNearAttractionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAttractionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAttraction", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DeleteAttractionRequestBody Body;
        
        public DeleteAttractionRequest()
        {
        }
        
        public DeleteAttractionRequest(ServiceReference1.DeleteAttractionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteAttractionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public DeleteAttractionRequestBody()
        {
        }
        
        public DeleteAttractionRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAttractionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAttractionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DeleteAttractionResponseBody Body;
        
        public DeleteAttractionResponse()
        {
        }
        
        public DeleteAttractionResponse(ServiceReference1.DeleteAttractionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteAttractionResponseBody
    {
        
        public DeleteAttractionResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchAttractionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchAttraction", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SearchAttractionRequestBody Body;
        
        public SearchAttractionRequest()
        {
        }
        
        public SearchAttractionRequest(ServiceReference1.SearchAttractionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchAttractionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public SearchAttractionRequestBody()
        {
        }
        
        public SearchAttractionRequestBody(string str)
        {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchAttractionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchAttractionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SearchAttractionResponseBody Body;
        
        public SearchAttractionResponse()
        {
        }
        
        public SearchAttractionResponse(ServiceReference1.SearchAttractionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchAttractionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Attraction[] SearchAttractionResult;
        
        public SearchAttractionResponseBody()
        {
        }
        
        public SearchAttractionResponseBody(ServiceReference1.Attraction[] SearchAttractionResult)
        {
            this.SearchAttractionResult = SearchAttractionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface WebService1SoapChannel : ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebService1Soap>, ServiceReference1.WebService1Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AttractionsNearStationsResponse> ServiceReference1.WebService1Soap.AttractionsNearStationsAsync(ServiceReference1.AttractionsNearStationsRequest request)
        {
            return base.Channel.AttractionsNearStationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AttractionsNearStationsResponse> AttractionsNearStationsAsync(ServiceReference1.station st)
        {
            ServiceReference1.AttractionsNearStationsRequest inValue = new ServiceReference1.AttractionsNearStationsRequest();
            inValue.Body = new ServiceReference1.AttractionsNearStationsRequestBody();
            inValue.Body.st = st;
            return ((ServiceReference1.WebService1Soap)(this)).AttractionsNearStationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.StationsNearAttractionsResponse> ServiceReference1.WebService1Soap.StationsNearAttractionsAsync(ServiceReference1.StationsNearAttractionsRequest request)
        {
            return base.Channel.StationsNearAttractionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StationsNearAttractionsResponse> StationsNearAttractionsAsync(ServiceReference1.Attraction at)
        {
            ServiceReference1.StationsNearAttractionsRequest inValue = new ServiceReference1.StationsNearAttractionsRequest();
            inValue.Body = new ServiceReference1.StationsNearAttractionsRequestBody();
            inValue.Body.at = at;
            return ((ServiceReference1.WebService1Soap)(this)).StationsNearAttractionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> CoolOrNotAsync()
        {
            return base.Channel.CoolOrNotAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DeleteAttractionResponse> ServiceReference1.WebService1Soap.DeleteAttractionAsync(ServiceReference1.DeleteAttractionRequest request)
        {
            return base.Channel.DeleteAttractionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeleteAttractionResponse> DeleteAttractionAsync(string str)
        {
            ServiceReference1.DeleteAttractionRequest inValue = new ServiceReference1.DeleteAttractionRequest();
            inValue.Body = new ServiceReference1.DeleteAttractionRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.WebService1Soap)(this)).DeleteAttractionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SearchAttractionResponse> ServiceReference1.WebService1Soap.SearchAttractionAsync(ServiceReference1.SearchAttractionRequest request)
        {
            return base.Channel.SearchAttractionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SearchAttractionResponse> SearchAttractionAsync(string str)
        {
            ServiceReference1.SearchAttractionRequest inValue = new ServiceReference1.SearchAttractionRequest();
            inValue.Body = new ServiceReference1.SearchAttractionRequestBody();
            inValue.Body.str = str;
            return ((ServiceReference1.WebService1Soap)(this)).SearchAttractionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52236/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52236/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
